{% set name = "minisom" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/MiniSom-{{ version }}.tar.gz
  sha256: b6850d5679e0e54dbc01028536168fca4c5ddc4621a79dc9ec8814b12d6aebdb

build:
  script: {{ PYTHON }} -m pip install . --no-build-isolation --no-deps -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy

test:
  imports:
    - minisom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JustGlowing/minisom
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Minimalistic implementation of the Self Organizing Maps (SOM)
  description: |
    MiniSom is a minimalistic and Numpy based implementation of the Self Organizing Maps (SOM)
  doc_url: https://github.com/JustGlowing/minisom/tree/master/examples
  dev_url: https://github.com/JustGlowing/minisom

extra:
  recipe-maintainers:
    - maclandrol
    
